#!/bin/bash
DATE=$(date +%Y%m%d-%H%M)
PWD=$(pwd)
ANYKERNEL="~/AnyKernel"
#ANYKERNEL="/home/mustaavalkosta/storage/AnyKernel"
OUTPUT="/media/glooms"
#OUTPUT="/home/mustaavalkosta/downloads/tests"
# cleanup
rm -v $ANYKERNEL/{kernel/zImage,system/lib/modules/*}
# copy files
find . -name "*.ko" -exec cp -v {} $ANYKERNEL/system/lib/modules/ \;
cp -v arch/arm/boot/zImage $ANYKERNEL/kernel/zImage
# zip it
cd $ANYKERNEL
zip -r9 $OUTPUT/kernel-$DATE.zip *
# return
cd $PWD
