obj-$(CONFIG_MACH_PRIMOU) += primou-panel.o
obj-$(CONFIG_MACH_SAGA) += saga-panel.o
obj-$(CONFIG_MACH_SPADE) += spade-panel.o
obj-$(CONFIG_MACH_VIVO) += vivow-panel.o
obj-$(CONFIG_MACH_VIVOW) += vivow-panel.o
obj-$(CONFIG_MACH_VISION) += vision-panel.o
